networks: #This is used if you have a reverse proxy. I use Nginx Proxy Manager but anything will do
  proxy: #You can remove this block if you are not planning to use a vpn
    external: true

services:
  lighthouse-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lighthouse-agent
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
          - proxy